# 超參數設定

BLOCK_SIZE = 20
BLOCK_GAP = 2
BLOCK_H_COUNT = 40
BLOCK_W_COUNT = 20

WINDOWS_MARGIN = 10
WINDOWS_HITHT = BLOCK_H_COUNT*BLOCK_SIZE + 2*WINDOWS_MARGIN
WINDOWS_WIDTH = BLOCK_W_COUNT*BLOCK_SIZE + 2*WINDOWS_MARGIN

DROP_EVENT = 555


GAME_STOP = 0
GAME_PLAY = 1
GAME_PAUSE = 2